/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    specialists: Specialist;
    'pricing-items': PricingItem;
    'equipment-items': EquipmentItem;
    'matkapital-steps': MatkapitalStep;
    reviews: Review;
    leads: Lead;
    'provider-sections': ProviderSection;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    specialists: SpecialistsSelect<false> | SpecialistsSelect<true>;
    'pricing-items': PricingItemsSelect<false> | PricingItemsSelect<true>;
    'equipment-items': EquipmentItemsSelect<false> | EquipmentItemsSelect<true>;
    'matkapital-steps': MatkapitalStepsSelect<false> | MatkapitalStepsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'provider-sections': ProviderSectionsSelect<false> | ProviderSectionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    organization: Organization;
    navigation: Navigation;
    homepage: Homepage;
    'notification-settings': NotificationSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    organization: OrganizationSelect<false> | OrganizationSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'notification-settings': NotificationSettingsSelect<false> | NotificationSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  /**
   * Ключ иконки, например brain, scan, message, book, heart
   */
  icon?: string | null;
  summary?: string | null;
  details?: string | null;
  symptoms?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        title: string;
        paragraphs?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  priceFrom?: string | null;
  sortOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialists".
 */
export interface Specialist {
  id: number;
  name: string;
  role: string;
  bio?: string | null;
  photo?: (number | null) | Media;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-items".
 */
export interface PricingItem {
  id: number;
  name: string;
  category: 'diagnostics' | 'classes';
  duration?: string | null;
  price: string;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment-items".
 */
export interface EquipmentItem {
  id: number;
  title: string;
  description?: string | null;
  icon?: string | null;
  image?: (number | null) | Media;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matkapital-steps".
 */
export interface MatkapitalStep {
  id: number;
  title: string;
  description?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  type: 'image' | 'text';
  image?: (number | null) | Media;
  name: string;
  text?: string | null;
  rating?: number | null;
  phone?: string | null;
  status: 'draft' | 'published';
  source: 'form' | 'admin';
  updatedAt: string;
  createdAt: string;
}
/**
 * Заявки с формы на сайте. Новые приходят в Telegram и на email.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  childAge?: string | null;
  message?: string | null;
  status: 'new' | 'in_progress' | 'done' | 'spam';
  source: 'contact_form' | 'admin';
  adminNote?: string | null;
  notifiedTelegram?: boolean | null;
  notifiedEmail?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider-sections".
 */
export interface ProviderSection {
  id: number;
  title: string;
  slug: string;
  scope: 'social' | 'education' | 'both';
  sortOrder?: number | null;
  blocks?:
    | (
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            items?:
              | {
                  label: string;
                  href?: string | null;
                  file?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'docs';
          }
        | {
            title?: string | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            lists?:
              | {
                  heading?: string | null;
                  items?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            docs?:
              | {
                  label: string;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'card';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  eyebrow?: string | null;
  description?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  body?: string | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'specialists';
        value: number | Specialist;
      } | null)
    | ({
        relationTo: 'pricing-items';
        value: number | PricingItem;
      } | null)
    | ({
        relationTo: 'equipment-items';
        value: number | EquipmentItem;
      } | null)
    | ({
        relationTo: 'matkapital-steps';
        value: number | MatkapitalStep;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'provider-sections';
        value: number | ProviderSection;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  summary?: T;
  details?: T;
  symptoms?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  priceFrom?: T;
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialists_select".
 */
export interface SpecialistsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-items_select".
 */
export interface PricingItemsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  duration?: T;
  price?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment-items_select".
 */
export interface EquipmentItemsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  image?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matkapital-steps_select".
 */
export interface MatkapitalStepsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  type?: T;
  image?: T;
  name?: T;
  text?: T;
  rating?: T;
  phone?: T;
  status?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  childAge?: T;
  message?: T;
  status?: T;
  source?: T;
  adminNote?: T;
  notifiedTelegram?: T;
  notifiedEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider-sections_select".
 */
export interface ProviderSectionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  scope?: T;
  sortOrder?: T;
  blocks?:
    | T
    | {
        heading?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        docs?:
          | T
          | {
              items?:
                | T
                | {
                    label?: T;
                    href?: T;
                    file?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        card?:
          | T
          | {
              title?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              lists?:
                | T
                | {
                    heading?: T;
                    items?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              docs?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  eyebrow?: T;
  description?: T;
  content?: T;
  body?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  fullName?: string | null;
  phone?: string | null;
  phoneHref?: string | null;
  email?: string | null;
  orgEmail?: string | null;
  city?: string | null;
  address?: string | null;
  addressShort?: string | null;
  workingHours?: string | null;
  website?: string | null;
  logo?: (number | null) | Media;
  vk?: string | null;
  ok?: string | null;
  telegram?: string | null;
  youtube?: string | null;
  maxBooking?: string | null;
  socialProviderUrl?: string | null;
  specialistsPage?: string | null;
  privacyPolicy?: string | null;
  rekvizityUrl?: string | null;
  promoVideoId?: string | null;
  mapEmbedUrl?: string | null;
  heroBadges?:
    | {
        id: string;
        label: string;
        icon?: string | null;
      }[]
    | null;
  aboutTitle?: string | null;
  aboutLead?: string | null;
  aboutBody?: string | null;
  aboutStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  aboutValues?:
    | {
        icon?: string | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization".
 */
export interface Organization {
  id: number;
  fullName?: string | null;
  shortName?: string | null;
  legalAddress?: string | null;
  postalAddress?: string | null;
  innKpp?: string | null;
  bank?: string | null;
  bik?: string | null;
  checkingAccount?: string | null;
  correspondentAccount?: string | null;
  registrationDate?: string | null;
  founder?: string | null;
  branches?: string | null;
  phones?: string | null;
  email?: string | null;
  semiStationary?: {
    title?: string | null;
    address?: string | null;
    transport?: string | null;
    schedule?:
      | {
          line: string;
          id?: string | null;
        }[]
      | null;
  };
  homeServices?: {
    title?: string | null;
    addresses?:
      | {
          address: string;
          transport?: string | null;
          id?: string | null;
        }[]
      | null;
    schedule?:
      | {
          line: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  topBarLinks?:
    | {
        href: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  navLinks?:
    | {
        href: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  layout?:
    | (
        | {
            eyebrow?: string | null;
            title?: string | null;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'about';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'equipment';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'matkapital';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'reviews';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
        | {
            title?: string | null;
            images?: (number | Media)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            anchor?: string | null;
            title?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            title?: string | null;
            items?:
              | {
                  label: string;
                  url?: string | null;
                  file?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'documents';
          }
        | {
            title: string;
            text?: string | null;
            buttonLabel: string;
            buttonHref: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Все настройки Telegram и Email для новых заявок с формы. Секреты хранятся в базе — не публикуйте их.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-settings".
 */
export interface NotificationSetting {
  id: number;
  telegramEnabled?: boolean | null;
  /**
   * Создайте бота у @BotFather и вставьте токен вида 123456:ABC-DEF...
   */
  telegramBotToken?: string | null;
  /**
   * Напишите боту /start, затем узнайте chat_id через @userinfobot или getUpdates.
   */
  telegramChatId?: string | null;
  emailEnabled?: boolean | null;
  notifyEmails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Например smtp.yandex.ru, smtp.mail.ru, smtp.gmail.com
   */
  smtpHost?: string | null;
  /**
   * Обычно 587 (STARTTLS) или 465 (SSL)
   */
  smtpPort?: number | null;
  smtpUser?: string | null;
  /**
   * Пароль приложения / пароль почтового ящика
   */
  smtpPass?: string | null;
  /**
   * Если пусто — используется SMTP логин
   */
  smtpFrom?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  fullName?: T;
  phone?: T;
  phoneHref?: T;
  email?: T;
  orgEmail?: T;
  city?: T;
  address?: T;
  addressShort?: T;
  workingHours?: T;
  website?: T;
  logo?: T;
  vk?: T;
  ok?: T;
  telegram?: T;
  youtube?: T;
  maxBooking?: T;
  socialProviderUrl?: T;
  specialistsPage?: T;
  privacyPolicy?: T;
  rekvizityUrl?: T;
  promoVideoId?: T;
  mapEmbedUrl?: T;
  heroBadges?:
    | T
    | {
        id?: T;
        label?: T;
        icon?: T;
      };
  aboutTitle?: T;
  aboutLead?: T;
  aboutBody?: T;
  aboutStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  aboutValues?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization_select".
 */
export interface OrganizationSelect<T extends boolean = true> {
  fullName?: T;
  shortName?: T;
  legalAddress?: T;
  postalAddress?: T;
  innKpp?: T;
  bank?: T;
  bik?: T;
  checkingAccount?: T;
  correspondentAccount?: T;
  registrationDate?: T;
  founder?: T;
  branches?: T;
  phones?: T;
  email?: T;
  semiStationary?:
    | T
    | {
        title?: T;
        address?: T;
        transport?: T;
        schedule?:
          | T
          | {
              line?: T;
              id?: T;
            };
      };
  homeServices?:
    | T
    | {
        title?: T;
        addresses?:
          | T
          | {
              address?: T;
              transport?: T;
              id?: T;
            };
        schedule?:
          | T
          | {
              line?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  topBarLinks?:
    | T
    | {
        href?: T;
        label?: T;
        id?: T;
      };
  navLinks?:
    | T
    | {
        href?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        equipment?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        matkapital?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        reviews?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              images?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              anchor?: T;
              title?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        documents?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    label?: T;
                    url?: T;
                    file?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              text?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-settings_select".
 */
export interface NotificationSettingsSelect<T extends boolean = true> {
  telegramEnabled?: T;
  telegramBotToken?: T;
  telegramChatId?: T;
  emailEnabled?: T;
  notifyEmails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  smtpHost?: T;
  smtpPort?: T;
  smtpUser?: T;
  smtpPass?: T;
  smtpFrom?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}